version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - json_data:/app/controllers/db
    environment:
      - FLASK_ENV=development

volumes:
  json_data:
